# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Alexandre Martins"
description: > # this means to ignore newlines until "email:"
   Tech Lead and Agile Coach. Currently helping build the technology vision and architecture of Globo's video streaming platform.

email: amartinsn@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: "Alexandre Martins"
author: "Alexandre Martins"
author_image: "/assets/images/author.jpg"
author_bio: "Tech Lead and Agile Coach. Currently helping build the technology vision and architecture of Globo's video streaming platform."

paginate:	5

url: "http://alexmartins.me"
baseurl: ""
#used to display twitter cards
twitter_handle: '@amartinsn'

#fill in disqus shortname to use disqus
disqus: alexmartins

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/amartinsn
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/amartinsn
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://linkedin.com/in/amartinsn
    desc:	View my LinkedIn profile
    share_url:
    share_title:
    share_link:
